package com.ryanconway.spaceflightnews.testutil

import com.ryanconway.spaceflightnews.domain.model.Article

object DummyData {

    val articles = listOf(
        Article(
            id = "6051e86631c42cd69c01e29a",
            title = "Russia looks to China as new space exploration partner",
            url = "https://spaceflightnow.com/2021/03/15/russia-looks-to-china-as-new-space-exploration-partner/",
            imageUrl = "https://mk0spaceflightnoa02a.kinstacdn.com/wp-content/uploads/2021/03/50875730681_b4e2d8c6cc_k.jpg",
            summary = "Russia’s decision to partner with China on a planned lunar research station, and not join the U.S.-led Artemis moon program, was disappointing after more than two decades of cooperation on the International Space Station, says NASA’s top human spaceflight official.",
            publishedAt = "2021-03-15T10:25:18.000Z",
        ),
        Article(
            id = "6051e86631c42cd69c01e29b",
            title = "SpaceX extends its own rocket reuse record on Starlink launch",
            url = "https://spaceflightnow.com/2021/03/14/spacex-extends-its-own-rocket-reuse-record-on-starlink-launch/",
            imageUrl = "https://mk0spaceflightnoa02a.kinstacdn.com/wp-content/uploads/2021/03/l21_1.jpg",
            summary = "Using a Falcon 9 booster flying for a record ninth time, SpaceX’s swift sequence of launches continued Sunday with a predawn liftoff from the Kennedy Space Center carrying another set of 60 Starlink internet satellites, the company’s third mission in 10 days.",
            publishedAt = "2021-03-14T10:25:18.000Z",
        ),
        Article(
            id = "6051e86631c42cd69c01e29c",
            title = "China launches spy satellite triplet for third time this year",
            url = "https://spaceflightnow.com/2021/03/14/china-launches-spy-satellite-triplet-for-third-time-this-year/",
            imageUrl = "https://mk0spaceflightnoa02a.kinstacdn.com/wp-content/uploads/2021/03/lm4cliftoff.jpg",
            summary = "Three Chinese military satellites launched Saturday aboard a Long March 4C rocket, joining six others China has sent into orbit since the start of the year on ocean surveillance missions.",
            publishedAt = "2021-03-14T10:25:18.000Z",
        ),
        Article(
            id = "6051e86631c42cd69c01e29d",
            title = "SpaceX rocket rolls out to pad 39A for next Starlink mission",
            url = "https://spaceflightnow.com/2021/03/13/spacex-rocket-rolls-out-to-pad-39a-for-next-starlink-mission/",
            imageUrl = "https://mk0spaceflightnoa02a.kinstacdn.com/wp-content/uploads/2021/03/starlink_stack.jpg",
            summary = "For the third time in 10 days, SpaceX is readying a Falcon 9 rocket for launch Sunday from Florida’s Space Coast with another 60 Starlink internet satellites. This time, SpaceX aims to extend the record for reusing a Falcon 9 booster to nine flights.",
            publishedAt = "2021-03-13T10:25:18.000Z",
        ),
        Article(
            id = "6051e86631c42cd69c01e29e",
            title = "Spacewalkers vent coolant lines and mate cables outside space station",
            url = "https://spaceflightnow.com/2021/03/13/us-eva-73/",
            imageUrl = "https://mk0spaceflightnoa02a.kinstacdn.com/wp-content/uploads/2021/03/EwYahUDWgAYaavi.jpg",
            summary = "Struggling with balky electrical connectors, spacewalker Mike Hopkins managed to plug in and secure three of four thick power and data cables Saturday that are needed by a European experiment platform, leaving one cable for additional troubleshooting.",
            publishedAt = "2021-03-13T10:25:18.000Z",
        ),
        Article(
            id = "6051e86631c42cd69c01e2a0",
            title = "Hubble resumes science observations after software error",
            url = "https://spaceflightnow.com/2021/03/12/hubble-resumes-science-observations-after-software-error/",
            imageUrl = "https://mk0spaceflightnoa02a.kinstacdn.com/wp-content/uploads/2015/04/s125e007257.jpg",
            summary = "NASA has partially restored the Hubble Space Telescope to science mode after a software error temporarily halted observations, but engineers continue studying a problem that kept the telescope’s aperture door from closing and a separate concern with Hubble’s main camera.",
            publishedAt = "2021-03-12T10:25:18.000Z",
        ),
        Article(
            id = "6051e86631c42cd69c01e29f",
            title = "Garbage pallet jettisoned from space station will stay in orbit two-to-four years",
            url = "https://spaceflightnow.com/2021/03/12/garbage-pallet-jettisoned-from-space-station-will-stay-in-orbit-two-to-four-years/",
            imageUrl = "https://mk0spaceflightnoa02a.kinstacdn.com/wp-content/uploads/2021/03/ep9.jpeg",
            summary = "NASA ground controllers sent commands to the International Space Station on Thursday for release of a 2.9-ton cargo pallet loaded with old batteries, the most massive object ever jettisoned from the orbiting outpost. The garbage carrier is expected to remain in orbit for two-to-four years before re-entering the atmosphere.",
            publishedAt = "2021-03-12T10:25:18.000Z",
        ),
        Article(
            id = "6051e86631c42cd69c01e2a1",
            title = "China’s Long March 7A rocket successful on second flight",
            url = "https://spaceflightnow.com/2021/03/12/chinas-long-march-7a-rocket-successful-on-second-flight/",
            imageUrl = "https://mk0spaceflightnoa02a.kinstacdn.com/wp-content/uploads/2021/03/lm7a.jpg",
            summary = "The second flight of China’s new medium-lift Long March 7A rocket successfully placed an experimental satellite into orbit Thursday, following a failed launch of the same configuration last year caused by a problem in a booster liquid oxygen system.",
            publishedAt = "2021-03-12T10:25:18.000Z",
        ),
        Article(
            id = "6051e86631c42cd69c01e2a2",
            title = "SpaceX adds more satellites to Starlink internet fleet",
            url = "https://spaceflightnow.com/2021/03/11/spacex-adds-more-satellites-to-starlink-internet-fleet/",
            imageUrl = "https://mk0spaceflightnoa02a.kinstacdn.com/wp-content/uploads/2021/03/starlink_l21_.jpg",
            summary = "Continuing a high-tempo launch cadence, SpaceX delivered another batch of 60 Starlink internet satellites to orbit early Thursday after a seemingly flawless liftoff from Cape Canaveral aboard a Falcon 9 rocket.",
            publishedAt = "2021-03-11T10:25:18.000Z",
        ),
        Article(
            id = "604046690d56f8001c3f7874",
            title = "Starship goes up. Starship goes down. But is the program moving forward?",
            url = "https://arstechnica.com/science/2021/03/starship-goes-up-starship-goes-down-but-is-the-program-moving-forward/",
            imageUrl = "https://cdn.arstechnica.net/wp-content/uploads/2021/03/SN10-Mar-3-2021-0265.jpg",
            summary = "\"One day, the true measure of success will be that Starship flights are commonplace.\"",
            publishedAt = "2021-03-04T02:20:09.000Z",
        ),
        Article(
            id = "604038530d56f8001c3f7871",
            title = "SpaceX to try again to launch long-delayed Starlink mission",
            url = "https://www.nasaspaceflight.com/2021/03/spacex-launch-delayed-starlink/",
            imageUrl = "https://www.nasaspaceflight.com/wp-content/uploads/2021/02/Starlink-L17.jpg",
            summary = "SpaceX is targeting Thursday, March 4 for the launch of the Starlink v1.0 L17 mission with a new batch of Starlink satellites from historic LC-39A at the Kennedy Space Center aboard a flight proven Falcon 9 booster.  The previous launch attempt on Sunday, February 28 ended in a scrub at T-1 minute 24 seconds.",
            publishedAt = "2021-03-04T01:23:49.000Z",
        ),
        Article(
            id = "6040177e0d56f8001c3f786b",
            title = "Biden’s first strategic guidance sets broad national security priorities",
            url = "https://spacenews.com/bidens-first-strategic-guidance-sets-broad-national-security-priorities/",
            imageUrl = "https://spacenews.com/wp-content/uploads/2021/03/Screen-Shot-2021-03-03-at-5.58.28-PM.png",
            summary = "President Joe Biden issued a national security blueprint that lays out broad goals and priorities for his administration.",
            publishedAt = "2021-03-03T23:10:54.000Z",
        ),
        Article(
            id = "6040152d0d56f8001c3f786a",
            title = "VIPER lunar rover mission cost increases",
            url = "https://spacenews.com/viper-lunar-rover-mission-cost-increases/",
            imageUrl = "https://spacenews.com/wp-content/uploads/2019/10/viper-470x470.jpg",
            summary = "A NASA rover mission to look for ice at the south pole of the moon has passed a key review, but now costs significantly more than previously advertised.",
            publishedAt = "2021-03-03T23:01:00.000Z",
        ),
        Article(
            id = "604007230d56f8001c3f7869",
            title = "Delayed Indonesian broadband satellite SATRIA fully funded",
            url = "https://spacenews.com/delayed-indonesian-broadband-satellite-satria-fully-funded/",
            imageUrl = "https://spacenews.com/wp-content/uploads/2021/03/SATRIA-Artist-View-_1100.jpg",
            summary = "Indonesia’s government has secured financing to continue manufacturing the SATRIA broadband satellite, although its intended orbital slot remains up in the air.",
            publishedAt = "2021-03-03T22:01:07.000Z",
        ),
        Article(
            id = "603ffdc80d56f8001c3f7868",
            title = "NASA to Provide Update on Perseverance ‘Firsts’ Since Mars Landing",
            url = "http://www.nasa.gov/press-release/nasa-to-provide-update-on-perseverance-firsts-since-mars-landing",
            imageUrl = "https://www.nasa.gov/sites/default/files/thumbnails/image/pia24421.jpg?itok=lATsFUV1",
            summary = "Since NASA’s Mars 2020 Perseverance rover touched down at Jezero Crater Feb. 18, mission controllers have made substantial progress as they prepare the rover for the unpaved road ahead.",
            publishedAt = "2021-03-03T21:21:00.000Z",
        ),
        Article(
            id = "603f8d53c2fab5001d1d6c8e",
            title = "SpaceX recycling vehicle for second Starship launch attempt [Updated]",
            url = "https://arstechnica.com/science/2021/03/spacex-set-for-its-third-major-starship-flight-test-on-wednesday/",
            imageUrl = "https://cdn.arstechnica.net/wp-content/uploads/2021/03/SN10-Mar-3-2021-1.jpg",
            summary = "Musk says he is confident Starship will be ready for a lunar flight in three years.",
            publishedAt = "2021-03-03T20:30:49.000Z",
        ),
        Article(
            id = "603fa95fc2fab5001d1d6c90",
            title = "Raymond: Space Force ‘not a political issue’",
            url = "https://spacenews.com/raymond-space-force-not-a-political-issue/",
            imageUrl = "https://spacenews.com/wp-content/uploads/2021/03/6395079.jpg",
            summary = "The White House unambiguous statement of support for the Space Force makes it “really clear that this is not a political issue, it’s an issue of national security,” Chief of Space Operations Gen. John Raymond.",
            publishedAt = "2021-03-03T15:21:03.000Z",
        ),
        Article(
            id = "603f8fa5c2fab5001d1d6c8f",
            title = "China to develop two super-heavy launchers for moon missions",
            url = "https://spacenews.com/china-to-develop-two-super-heavy-launchers-for-moon-missions/",
            imageUrl = "https://spacenews.com/wp-content/uploads/2018/11/new-concept-launch-vehicle-human-spaceflight-Zhuhai-2018-CASC-copy.jpg",
            summary = "China will work on development of two types of super-heavy launch vehicles for future lunar projects, a senior official said Wednesday.",
            publishedAt = "2021-03-03T13:31:17.000Z",
        ),
        Article(
            id = "603f83edc2fab5001d1d6c8d",
            title = "Eastern Range looks for ways to support additional launches",
            url = "https://spacenews.com/eastern-range-looks-for-ways-to-support-additional-launches/",
            imageUrl = "https://spacenews.com/wp-content/uploads/2021/03/f9-doublelaunch.jpg",
            summary = "As launch activity grows on the Eastern Range in Florida, companies and government agencies are looking at ways to add capacity, largely through incremental improvements.",
            publishedAt = "2021-03-03T12:41:17.000Z",
        ),
        Article(
            id = "603f6ec4c2fab5001d1d6c8c",
            title = "Australian startup develops quantum sensors for space applications",
            url = "https://spacenews.com/australian-startup-develops-quantum-sensors-for-space-applications/",
            imageUrl = "https://spacenews.com/wp-content/uploads/2021/03/rsz_fleet_space_technologies_nanosatellite_earth.jpg",
            summary = "Q-Ctrl, an Australian startup, is developing quantum sensors to send to Earth orbit, the moon and eventually Mars.",
            publishedAt = "2021-03-03T11:11:00.000Z",
        )
    )
}